{{- /*
  vim:ft=yaml.gotmpl:
    */ -}}

---

{{- range (list "InconsolataLGC" "Meslo") }}
'{{- joinPath (substr 0 1 . | lower) . -}}':
  url: {{ printf "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/%s.tar.xz" . | quote }}
  type: 'archive'
  executable: true
  refreshPeriod: '720h' # 30 days
  exclude:
    # - '*NerdFontMono*'
    # - '*NFM*'
    - '*NerdFontPropo*'
    - '*NFP*'
{{- end }}
    - '*DZ*'
    - '*LGM*'
    - '*LGL*'
