{{- /*
  vim:ft=yaml.gotmpl:
    */ -}}

---

{{- range (list "InconsolataLGC" "FiraCode" "Meslo") }}
'{{- joinPath (substr 0 1 . | lower) . -}}':
  url: {{ printf "%s.tar.xz" . | gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" | quote }}
  type: 'archive'
  executable: true
  refreshPeriod: '720h' # 30 days
  exclude:
    # - '*NerdFontMono*'
    # - '*NFM*'
    - '*NerdFontPropo*'
    - '*NFP*'
{{- end }}
    - '*DZ*'
    - '*LGM*'
    - '*LGL*'
