name: yadr
services:
  dotfiles:
    environment:
      IMAGE_NAME: &imageTag "yadr"
    container_name: yadr
    build:
      context: .
      args:
        DEBIAN_FRONTEND: noninteractive
      tags:
        - *imageTag
    image: *imageTag
    volumes:
      - ./:/root/.yadr/
      - plugged:/root/.yadr/root/vim/plugged
      - zprezto:/root/.zprezto
volumes:
  plugged:
  zprezto:
