{{- /*
  vim:ft=yaml.gotmpl:
    */ -}}

---
# ASDF <https://asdf-vm.com>
{{- $arch := "amd64" }}
{{- if ne .chezmoi.arch $arch }}
{{-   $arch = .chezmoi.arch }}
{{- end }}
'asdf':
  url: {{ printf `asdf-*-linux-%s.tar.gz` $arch | gitHubLatestReleaseAssetURL "asdf-vm/asdf" | quote }}
  type: 'archive-file'
  executable: true
  refreshPeriod: '168h' # 7 days
  path: 'asdf'
