# Based on https://github.com/morhetz/gruvbox by morhetz <morhetz@gmail.com>
# Adapted to kitty by wdomitrz <witekdomitrz@gmail.com>

background              #002b36
foreground              #657b83

cursor                  #93a1a1

selection_background    #586e75
selection_foreground    #93a1a1

# black
color0                  #073642
color8                  #002b36

# red
color1                  #dc322f
# light red
color9                  #cb4b16

#: green
color2                  #859900
# light green
color10                 #586e75

# yellow
color3                  #b58900
# light yellow
color11                 #657b83

# blue
color4                  #268bd2
# light blue
color12                 #839496

# purple
color5                  #d33682
# light purple
color13                 #6c71c4

# aqua
color6                  #2aa198
# lighy aqua
color14                 #93a1a1

# white
color7                  #eee8d5
color15                 #fdf6e3
