[calming]
profile-desc=Calming volume profile
video=no
volume=70.0

[big-cache]
profile-desc=Big cache, on disc
cache=yes
cache-pause=no
cache-dir=~/.cache/mpv
cache-on-disk=yes
demuxer-max-bytes=500M
#demuxer-max-bytes=123400KiB
demuxer-max-back-bytes=100M
demuxer-readahead-secs=60

[verbose-speed]
profile-desc=video aceleration debug
# use mpv -v to discover module
# fatal error warn info status v debug trace
msg-level=vo/gpu=v
speed=2.0

[vim-term]
profile=big-cache
profile-desc=No terminal output
force-window=immediate
no-terminal

[vim-term-1.5]
profile=vim-term
profile-desc=No terminal output and 1.5x speed
speed=1.5

[vim-term-2.0]
profile=vim-term
profile-desc=No terminal output and 2.0x speed
speed=2.0

