; Global settings for {{ .program }}
[ {{- .global -}} ]
; Set the day and night screen temperatures
temp-day=6500
temp-night=4500
; temp-day=5700
; temp-night=3500

; Disable the smooth fade between temperatures when {{ .program }} starts and stops.
; 0 will cause an immediate change between screen temperatures.
; 1 will gradually apply the new screen temperature over a couple of seconds.
fade=1

; Solar elevation thresholds.
; By default, {{ .program }} will use the current elevation of the sun to determine
; whether it is daytime, night or in transition (dawn/dusk). When the sun is
; above the degrees specified with elevation-high it is considered daytime and
; below elevation-low it is considered night.
;elevation-high=3
;elevation-low=-6

; Enable smooth transition
transition=1

; Custom dawn/dusk intervals.
; Instead of using the solar elevation, the time intervals of dawn and dusk
; can be specified manually. The times must be specified as HH:MM in 24-hour
; format.
dawn-time=04:30-06:30
dusk-time=16:15-18:15

; Set the screen brightness. Default is 1.0.
;brightness=0.9
; It is also possible to use different settings for day and night
; since version 1.8.
{{ if eq .hostname "netha-A14CR" -}}
brightness-day=0.85
brightness-night=0.6
{{- else -}}
;brightness-day=0.9
brightness-night=0.85
{{- end }}
; Set the screen gamma (for all colors, or each color channel
; individually)
;gamma=0.8
;gamma=0.8:0.7:0.8
; This can also be set individually for day and night since
; version 1.10.
;gamma-day=0.8:0.7:0.8
gamma-night=0.9:0.8:0.9

; Set the location-provider: 'geoclue2', 'manual'
; type '{{ .program }} -l list' to see possible values.
; The location provider settings are in a different section.
location-provider=manual

{{ .adjustment.comment -}}
; The adjustment method settings are in a different section.
adjustment-method={{- .adjustment.method }}
;adjustment-method=wayland

; Configuration of the location-provider:
; type '{{ .program }} -l PROVIDER:help' to see the settings.
; ex: '{{ .program }} -l manual:help'
; Keep in mind that longitudes west of Greenwich (e.g. the Americas)
; are negative numbers.
[manual]
lat=-12.9245769
lon=-38.3710355

; Configuration of the adjustment-method
; type '{{ .program }} -m METHOD:help' to see the settings.
; ex: '{{ .program }} -m randr:help'
; In this example, randr is configured to adjust screen 1.
; Note that the numbering starts from 0, so this is actually the second screen.
; If this option is not specified, {{ .program }} will try to adjust _all_
; screens.
[randr]
screen=0
;crtc=0

[drm]
crtc=0

