source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "github-pages", group: :jekyll_plugins

gem "just-the-docs", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-tidy"
end

if RUBY_VERSION >= "3.0"
  gem "webrick"
end
