source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "jekyll", "~> 4.3.2"

gem "just-the-docs", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-tidy"

  gem "jekyll-coffeescript"
  gem "jekyll-default-layout"
  gem "jekyll-optional-front-matter"
  gem "jekyll-paginate"
  gem "jekyll-readme-index"
  gem "jekyll-titles-from-headings"
  gem "jekyll-relative-links"

  gem "jekyll-redirect-from"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

if RUBY_VERSION >= "3.0"
  gem "webrick"
end
