name: CI

on:
  push:
    branches:
      - "main"
      - "mine"
  pull_request:
    branches:
      - "main"
      - "friends"
  workflow_dispatch:

jobs:
  clone-and-install:

    strategy:
      matrix:
        ubuntu-os:
          - 20
          - 22
          - 24

    runs-on: ubuntu-${{ matrix.ubuntu-os }}

    env:
      CODESPACES: true

    steps:
    - uses: actions/checkout@v3

    - name: install
      run: ./install.sh

    - name: chezmoi data
      run: './root/bin/chezmoi data --format yaml'

    - name: chezmoi managed
      run: './root/bin/chezmoi managed -i all'

    - name: installed font files
      run: 'ls -lha ~/.local/share/fonts/**/*/'

